"""
Per-asset research source list.

These are the canonical sources to consult each week for that asset. The
dashboard renders them so the user can see what's being watched; a future
news-scan agent (running server-side, weekly) will pull from these and
synthesize "what's changed this week" into the narratives.

Categories:
  - "official": government, central bank, multilateral data releases (the
                authoritative numbers)
  - "industry": industry bodies, exchange data, dedicated trackers
  - "research": investment-bank research, consultancies, think-tanks
  - "news":     financial news publications and beats
  - "data":     real-time market data / on-chain analytics

Format: list of dicts with name, category, and a brief note on what to look for.
"""

SOURCES = {

    # ─── METALS ─────────────────────────────────────────────────────────────
    "gold": [
        {"name": "World Gold Council — Gold Demand Trends", "category": "industry",
         "note": "Quarterly demand-side breakdown: central bank purchases, jewelry, technology, ETF flows. Most authoritative single source."},
        {"name": "World Gold Council — Central Bank Statistics", "category": "industry",
         "note": "Monthly reported central bank purchases by country; lag of ~2 months."},
        {"name": "IMF International Financial Statistics — Reserves", "category": "official",
         "note": "Official central bank gold holdings; cross-check against WGC reported purchases."},
        {"name": "CFTC Commitments of Traders — Gold", "category": "official",
         "note": "Friday release for prior Tuesday: speculative positioning in COMEX gold futures."},
        {"name": "SPDR Gold Trust (GLD) holdings", "category": "data",
         "note": "Daily-updated ETF holdings; proxy for Western financial demand."},
        {"name": "FRED — 10Y TIPS yield (DFII10)", "category": "official",
         "note": "The traditional macro variable for gold; broken since 2022 but still worth watching for restoration."},
        {"name": "Shanghai Gold Exchange premium", "category": "data",
         "note": "Premium of SGE over London signals tightness in Chinese physical market."},
        {"name": "PBoC monthly reserve announcements", "category": "official",
         "note": "China's reported gold reserves; many believe actual holdings exceed disclosed figures."},
    ],
    "silver": [
        {"name": "Silver Institute — World Silver Survey", "category": "industry",
         "note": "Annual: comprehensive supply/demand balance, industrial breakdown, stocks-to-use."},
        {"name": "Silver Institute — Interim Reports", "category": "industry",
         "note": "Mid-year update on the annual balance."},
        {"name": "COMEX silver inventories", "category": "data",
         "note": "Registered and eligible stocks at COMEX warehouses; persistent drawdowns signal tightness."},
        {"name": "LBMA vault holdings — silver", "category": "data",
         "note": "London vaulted silver, monthly disclosure; the other major above-ground inventory."},
        {"name": "CFTC Commitments of Traders — Silver", "category": "official",
         "note": "Speculative positioning in COMEX silver futures."},
        {"name": "BloombergNEF / IEA — Solar PV installations", "category": "research",
         "note": "Solar is the largest growing silver demand vector; installation data drives the structural deficit thesis."},
    ],
    "copper": [
        {"name": "International Copper Study Group (ICSG) — Monthly Bulletin", "category": "industry",
         "note": "Monthly global supply/demand balance; the authoritative figure on the deficit."},
        {"name": "LME / COMEX / SHFE inventories", "category": "data",
         "note": "Daily exchange stocks; concurrent drawdowns across all three signal genuine tightness."},
        {"name": "TC/RC (treatment & refining charges)", "category": "data",
         "note": "Smelter fees for processing concentrate; falling TC/RCs signal smelter competition for scarce concentrate — a real-time mine-tightness indicator."},
        {"name": "China NBS — fixed asset investment, property data", "category": "official",
         "note": "Monthly data on Chinese property and infrastructure activity, the dominant cyclical copper demand driver."},
        {"name": "China customs — copper and concentrate imports", "category": "official",
         "note": "Monthly import data; surges signal strong Chinese demand."},
        {"name": "BloombergNEF — Grid investment, EV adoption", "category": "research",
         "note": "Structural demand vectors driving the long-term thesis."},
        {"name": "Goldman Sachs Commodities Research", "category": "research",
         "note": "Long-standing copper deficit-thesis advocacy; tracks supply pipeline and disruptions."},
    ],

    # ─── ENERGY ─────────────────────────────────────────────────────────────
    "oil": [
        {"name": "EIA Weekly Petroleum Status Report", "category": "official",
         "note": "Wednesday 10:30 ET (Thursday if holiday): crude stocks, gasoline, distillates, refinery utilization. The most market-moving weekly print."},
        {"name": "EIA Short-Term Energy Outlook (STEO)", "category": "official",
         "note": "Monthly; supply-demand projections, US production forecast."},
        {"name": "IEA Monthly Oil Market Report (OMR)", "category": "official",
         "note": "Authoritative monthly: demand forecasts, OECD inventories, OPEC+ compliance."},
        {"name": "OPEC Monthly Oil Market Report (MOMR)", "category": "official",
         "note": "OPEC's view of the market; secondary sources estimate OPEC production."},
        {"name": "OPEC+ ministerial meetings", "category": "official",
         "note": "Quota and policy decisions; calendar-known events that can move the market."},
        {"name": "Baker Hughes weekly rig count", "category": "industry",
         "note": "Friday: leading indicator for US shale supply response."},
        {"name": "CFTC Commitments of Traders — WTI Crude", "category": "official",
         "note": "Managed-money positioning in NYMEX WTI."},
        {"name": "Goldman Sachs / JP Morgan oil research", "category": "research",
         "note": "Major-bank S/D balances and price forecasts; often market-moving."},
        {"name": "Russia/Iran sanctions enforcement updates", "category": "news",
         "note": "Reuters/Bloomberg coverage of OFAC and EU actions; affects available sanctioned barrels."},
    ],
    "natgas": [
        {"name": "EIA Weekly Natural Gas Storage Report", "category": "official",
         "note": "Thursday 10:30 ET: working gas in storage; the dominant weekly data point. Five-year-average comparison is the key reference."},
        {"name": "EIA Natural Gas Weekly Update", "category": "official",
         "note": "Same release: production, demand, prices, weather context."},
        {"name": "NOAA — 6-10 day and 8-14 day weather outlooks", "category": "official",
         "note": "Weather is the dominant short-term price driver; HDD and CDD forecasts."},
        {"name": "LNG terminal feedgas data", "category": "data",
         "note": "Sabine Pass, Cameron, Corpus Christi, Freeport feedgas demand; outages and ramps move Henry Hub."},
        {"name": "Bloomberg / S&P Global LNG export tracker", "category": "industry",
         "note": "Cargo schedules, destination flows; ties US prices to global TTF/JKM."},
        {"name": "PJM / ERCOT load forecasts", "category": "data",
         "note": "Power-sector gas demand; data-center load growth a structural new vector."},
        {"name": "European TTF / Asian JKM prices", "category": "data",
         "note": "Global gas benchmarks; arbitrage with Henry Hub via LNG."},
    ],
    "agri": [
        {"name": "USDA World Agricultural Supply and Demand Estimates (WASDE)", "category": "official",
         "note": "Monthly (~10th-12th): global S/D balances for corn, soy, wheat, cotton, sugar, rice. The most-watched agri data release."},
        {"name": "USDA Crop Progress Report", "category": "official",
         "note": "Weekly during growing season: planting, condition, harvest progress in the US."},
        {"name": "USDA Foreign Agricultural Service — Production, Supply, Distribution", "category": "official",
         "note": "Country-level granular data."},
        {"name": "Brazil CONAB monthly estimates", "category": "official",
         "note": "Brazilian crop estimates, often divergent from USDA — a major source of S/D revision."},
        {"name": "Black Sea trade flows — Reuters / SovEcon", "category": "news",
         "note": "Russia and Ukraine wheat exports; geopolitically sensitive."},
        {"name": "NOAA — El Niño / La Niña status (ENSO)", "category": "official",
         "note": "Macro weather pattern affecting multi-season growing conditions globally."},
        {"name": "International Cocoa Organization, ICO Coffee Reports", "category": "industry",
         "note": "For softs: West African cocoa supply disease, Brazil coffee weather."},
    ],

    # ─── CRYPTO ─────────────────────────────────────────────────────────────
    "btc": [
        {"name": "Farside Investors — Bitcoin ETF flow tracker", "category": "data",
         "note": "Daily-updated net flows for all US spot Bitcoin ETFs; the most-watched single demand signal."},
        {"name": "Glassnode on-chain analytics", "category": "data",
         "note": "Long-term holder supply, exchange balances, MVRV, realized cap; the canonical on-chain dashboard."},
        {"name": "CryptoQuant", "category": "data",
         "note": "Exchange flows, miner activity, derivatives positioning; complementary to Glassnode."},
        {"name": "MicroStrategy / Strategy 8-K filings", "category": "official",
         "note": "Corporate treasury purchases; largest single non-ETF buyer."},
        {"name": "Coin Metrics — Network data", "category": "data",
         "note": "Hashrate, difficulty, transaction count; network-health metrics."},
        {"name": "BitMEX / Deribit funding rates and open interest", "category": "data",
         "note": "Derivatives positioning; sustained extreme funding signals crowded positioning."},
        {"name": "Galaxy Digital, Coinbase Institutional research", "category": "research",
         "note": "Institutional-quality crypto research."},
        {"name": "SEC enforcement actions, court filings", "category": "official",
         "note": "Regulatory developments; major source of binary outcomes for the asset class."},
    ],
    "eth": [
        {"name": "Farside Investors — Ethereum ETF flow tracker", "category": "data",
         "note": "Daily net flows for US spot ETH ETFs; lagging BTC ETF demand."},
        {"name": "L2Beat — Layer-2 TVL and activity", "category": "data",
         "note": "Total value locked across L2s; the value-capture debate hinges on whether L2 activity translates to ETH demand."},
        {"name": "DefiLlama — DeFi TVL", "category": "data",
         "note": "DeFi total value locked, broken down by protocol and chain."},
        {"name": "Ultrasound.money", "category": "data",
         "note": "ETH supply, burn rate, staking ratio; the canonical 'is ETH deflationary right now' tracker."},
        {"name": "Ethereum Foundation blog, EIP repository", "category": "official",
         "note": "Protocol upgrades (Pectra, Fusaka, etc.); supply mechanics."},
        {"name": "RWA.xyz", "category": "data",
         "note": "Real-world asset tokenization on Ethereum and other chains."},
    ],
    "sol": [
        {"name": "Solana validators dashboard", "category": "data",
         "note": "Network uptime, validator distribution, staking ratio."},
        {"name": "DefiLlama — Solana TVL and DEX volume", "category": "data",
         "note": "Solana ecosystem activity; DEX volume periodically rivals Ethereum's."},
        {"name": "Jupiter / Raydium DEX statistics", "category": "data",
         "note": "Trading activity on Solana's dominant DEX aggregators."},
        {"name": "Helius / Solana RPC providers", "category": "data",
         "note": "Network performance, transaction throughput, congestion events."},
        {"name": "Firedancer development updates (Jump Crypto)", "category": "official",
         "note": "Independent validator client; improves performance and decentralization."},
        {"name": "SEC ETF filings — Solana", "category": "official",
         "note": "Solana spot ETF applications; major prospective demand catalyst."},
        {"name": "Helium / Render / DePIN protocol metrics", "category": "data",
         "note": "DePIN traction is a key consumer-app vector for Solana."},
    ],
    "zec": [
        {"name": "Zcash Community / ECC blog", "category": "official",
         "note": "Protocol upgrades, governance, shielded-pool roadmap."},
        {"name": "Shielded pool supply tracker", "category": "data",
         "note": "Share of ZEC in shielded pools; core privacy adoption metric."},
        {"name": "Exchange listing/delisting announcements", "category": "news",
         "note": "Privacy coins face periodic delistings on AML grounds; existential to liquidity."},
        {"name": "FATF / FinCEN privacy-coin guidance", "category": "official",
         "note": "Regulatory developments at the global level."},
        {"name": "Grayscale Zcash Trust (ZCSH) flows", "category": "data",
         "note": "Limited institutional channel; small but a signal."},
    ],

    # ─── REAL ESTATE ────────────────────────────────────────────────────────
    "us_re": [
        {"name": "NAREIT — T-Tracker, FFO data", "category": "industry",
         "note": "Quarterly aggregated REIT operating metrics; the authoritative industry numbers."},
        {"name": "Green Street Advisors — Commercial Property Price Index", "category": "research",
         "note": "Private commercial real estate values; lag of weeks to months but methodologically rigorous."},
        {"name": "MSCI Real Capital Analytics — Transaction volumes", "category": "research",
         "note": "Transaction activity; bid-ask gap signals."},
        {"name": "FDIC Quarterly Banking Profile", "category": "official",
         "note": "Bank CRE exposure, delinquencies, charge-offs; regional bank concentration risk."},
        {"name": "Federal Reserve H.8 Bank Credit", "category": "official",
         "note": "Weekly bank balance sheet data including CRE loans."},
        {"name": "MBA Commercial/Multifamily Mortgage Bankers Performance Report", "category": "industry",
         "note": "Origination volumes, refinancing activity."},
        {"name": "Kastle Systems Back-to-Office Index", "category": "data",
         "note": "Office occupancy proxy across major metros."},
        {"name": "DC BLOX, Synergy Research Group — Data center capacity", "category": "research",
         "note": "Data center supply/demand for the growing structural-winner segment."},
        {"name": "Trepp — CMBS delinquency data", "category": "industry",
         "note": "Commercial mortgage-backed securities delinquencies; CRE credit stress indicator."},
    ],
    "intl_re": [
        {"name": "EPRA — European Public Real Estate", "category": "industry",
         "note": "European listed real estate body; aggregate data and research."},
        {"name": "Japan Real Estate Institute, Tokyo Office Market Reports", "category": "industry",
         "note": "Tokyo office vacancies and rents; Japan property fundamentals."},
        {"name": "Knight Frank / JLL / Savills global market reports", "category": "research",
         "note": "Major brokerages publish global office, residential, logistics reports."},
        {"name": "China NBS — 70-city property prices", "category": "official",
         "note": "Monthly Chinese residential prices; gauge of property-crisis trajectory."},
        {"name": "Country Garden / Vanke / Evergrande disclosures", "category": "official",
         "note": "Chinese property developer financial disclosures; bellwethers of crisis."},
        {"name": "Bank of Japan quarterly Tankan", "category": "official",
         "note": "Includes commercial property indicators."},
    ],

    # ─── REGIONAL EQUITY ────────────────────────────────────────────────────
    "em": [
        {"name": "IIF — Capital Flows Tracker", "category": "research",
         "note": "Weekly EM portfolio flows (equity and debt); the cleanest read on positioning."},
        {"name": "EPFR — Fund flows by region", "category": "data",
         "note": "Mutual fund flow data; positioning vs benchmark."},
        {"name": "MSCI EM index constituent disclosures", "category": "data",
         "note": "Country and sector weights; understanding what 'EM' actually is."},
        {"name": "JP Morgan EM Bond Index spreads (EMBI)", "category": "data",
         "note": "Sovereign credit spreads; EM credit stress feeds EM equities."},
        {"name": "TIC Treasury International Capital", "category": "official",
         "note": "Foreign holdings of US securities, US holdings of foreign — flow data with lag."},
        {"name": "RBI, BSP, Banxico, BCB minutes", "category": "official",
         "note": "Major EM central banks; rate path vs Fed drives currency and equity flows."},
        {"name": "Goldman / Morgan Stanley / GMO EM research", "category": "research",
         "note": "Established EM strategist communities."},
    ],
    "china": [
        {"name": "China NBS Monthly Activity Data", "category": "official",
         "note": "Industrial production, retail sales, fixed asset investment; the monthly economic pulse."},
        {"name": "China PMI — official (NBS) and Caixin", "category": "official",
         "note": "Manufacturing and services PMI; NBS vs Caixin differential informative."},
        {"name": "PBoC monetary policy statements, MLF operations", "category": "official",
         "note": "Policy easing magnitude and pace."},
        {"name": "China Politburo, Central Economic Work Conference readouts", "category": "official",
         "note": "Major political signal events for direction-setting on stimulus and reform."},
        {"name": "Stock Connect daily flows (Northbound/Southbound)", "category": "data",
         "note": "Daily foreign and Hong Kong-mainland flows; positioning signal."},
        {"name": "China property data — sales, starts, prices", "category": "official",
         "note": "Continued property weakness has been the central drag on Chinese sentiment."},
        {"name": "US Treasury, Commerce Department — China actions", "category": "official",
         "note": "Tariffs, export controls, sanctions; geopolitical risk vector."},
        {"name": "CICC, CSC, Citic research", "category": "research",
         "note": "Onshore-perspective China equity research."},
    ],

    # ─── CURRENCIES ─────────────────────────────────────────────────────────
    "dxy": [
        {"name": "Federal Reserve FOMC statements, minutes, projections", "category": "official",
         "note": "Fed policy path is the master dollar variable."},
        {"name": "BLS Employment Situation, CPI; BEA PCE, GDP", "category": "official",
         "note": "Major US data shapes Fed expectations and the dollar."},
        {"name": "FRED — Trade Weighted U.S. Dollar Index", "category": "official",
         "note": "Broader than DXY; tracks against trading partners."},
        {"name": "BIS US Dollar Cross-Border Banking Statistics", "category": "official",
         "note": "Quarterly: global dollar funding conditions; flags stress in offshore dollar markets."},
        {"name": "CFTC Commitments of Traders — Dollar index futures", "category": "official",
         "note": "Speculative dollar positioning."},
        {"name": "Fed swap line activity", "category": "official",
         "note": "Dollar-shortage indicator; usage in stress periods."},
        {"name": "BRICS summit declarations, sanctions news", "category": "news",
         "note": "Long-tail de-dollarization narrative; weight of declarations vs actual flows."},
    ],
    "eur": [
        {"name": "ECB Monetary Policy Statements, Minutes, SMA", "category": "official",
         "note": "ECB path vs Fed is the dominant EUR/USD variable."},
        {"name": "Eurostat — HICP, Industrial Production, GDP", "category": "official",
         "note": "Eurozone data; relative growth vs US."},
        {"name": "German Bundesbank reports, Ifo, ZEW surveys", "category": "official",
         "note": "Germany is the eurozone's largest economy; its data dominates."},
        {"name": "Italian/Spanish/French sovereign spreads (BTP-Bund, etc.)", "category": "data",
         "note": "Peripheral spread widening signals cohesion stress; can pressure EUR."},
        {"name": "ECB TLTRO operations, balance sheet data", "category": "official",
         "note": "Eurozone liquidity conditions."},
        {"name": "TTF natural gas prices", "category": "data",
         "note": "Energy import dependence makes EUR sensitive to European gas prices."},
    ],
    "jpy": [
        {"name": "Bank of Japan policy statements, minutes, outlook reports", "category": "official",
         "note": "BoJ normalization pace is the structural JPY variable."},
        {"name": "Japan Ministry of Finance — FX intervention disclosures", "category": "official",
         "note": "Monthly disclosure (with lag); MoF rhetoric is the near-term intervention signal."},
        {"name": "Japan CPI, shunto wage data", "category": "official",
         "note": "Wage-price spiral evidence supports BoJ normalization."},
        {"name": "JGB yields, 10Y in particular", "category": "data",
         "note": "End of YCC; JGB yields freely move and inform JPY."},
        {"name": "JPY carry-trade positioning estimates (CFTC speculator data)", "category": "data",
         "note": "Net short JPY in CME futures as carry positioning proxy."},
        {"name": "Japan investor outflows — MoF International Transactions in Securities", "category": "official",
         "note": "Weekly data on Japanese investor purchases of foreign securities; carry-trade activity proxy."},
    ],
    "cny": [
        {"name": "PBoC daily USD/CNY central parity fix", "category": "official",
         "note": "9:15 AM Beijing time daily; the policy signal. Persistent fixes weaker than market expectation signal depreciation tolerance."},
        {"name": "PBoC monetary policy report", "category": "official",
         "note": "Quarterly; broader framework and intentions."},
        {"name": "China customs trade data", "category": "official",
         "note": "Trade surplus magnitude is the structural CNY support."},
        {"name": "SAFE — capital flow data", "category": "official",
         "note": "Monthly cross-border capital flows."},
        {"name": "CNH-CNY spread (offshore vs onshore yuan)", "category": "data",
         "note": "Real-time gauge of market pressure on the managed onshore rate."},
        {"name": "USTR / Commerce — tariff announcements", "category": "official",
         "note": "Tariffs trigger CNY weakening response from PBoC; primary geopolitical risk channel."},
        {"name": "Yi Gang / Pan Gongsheng public statements", "category": "official",
         "note": "PBoC leadership rhetoric on currency stability commitment."},
    ],
}
